### PR TITLE
Added getcommand function

### PR DESCRIPTION
**Pull request by Parthav46**
this function contains key press handlers

### CODE REVIEW

**Comment by Parthav46** [comment]
This PR also contain that Makefile implementation. To build the project run
`make build`
and to run it
`make run` or `./chell`

**Comment by Satharus** [comment]
Thanks a lot for your effort! I really really appreciate it.

**Comment by Parthav46** [comment]
Just refering #3 and #6 for a record

**Comment by Satharus** [comment]
@Parthav46  I've updated the base in 61969823f63097bcaf152d41ff9d729f2bf193a2. Now I think both of us can work simultaneously without any conflicts. I'll handle the command line editing and you can continue working on the history :D 

If you have any changes you want to make please tell me. 

Thank you so so much for your help!

**Comment by Parthav46** [comment]
@Satharus should I make implementation for doubly linked list before starting

**Comment by Satharus** [comment]
I think we should make it after, continue working on the history part for now please

**Pull request merged**
