### PR TITLE
Added Chell command history

### LINKED ISSUE #3: Add command history
Add command history like in BASH where you can use arrow up and arrow down to cycle previously run commands.

### PR DESCRIPTION
**Pull request by Parthav46**
Added functionality to get previously ran commands on Up/Down arrow press.
Fixes #3 
Tasks:
- [x] get previous command on up arrow key press
- [x] get next command on down arrow key press
- [x] commands are saved to `~/.chell_history` after quit
- [x] commands are loaded from `~/.chell_history` if file exists
- [x] code documentation and formating
- [x] pull from master and resolve any conflict

Known Bugs:
- For the first command to be executed on chell the getNext is not getting buffer pointer correctly (getPrev works perfectly)
- If history log file doesn't exist it getNext function returns garbage value (getPrev works perfectly)

### CODE REVIEW

**Comment by Satharus** [comment]
@Parthav46  Thanks a lot! Amazing work, man. 

I have checked out the conflicts and merged the pull request now :D!

**Comment by Parthav46** [comment]
@Satharus 
you merged it
I was going to solve the bugs in this same PR

**Comment by Satharus** [comment]
it's okay, there are a couple of linker errors right now which I am trying to resolve and I'll make a commit after it. 

You can fix the bugs in another PR no problems!

**Comment by Satharus** [comment]
Hey @Parthav46  

I've done some minor edits and tried to get the program to link properly but it still wouldn't 

Could you please fix this and make another PR or refrain from using global variables all-together?  

Thanks!

Edit: I am getting a multiple definitions error, sorry for not mentioning that at first.

**Comment by Satharus** [comment]
I fixed the multiple definitions errors and changed the makefile, it should work fine now.

**Pull request merged**
